// <auto-generated />
using AgendaContactos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaContactos.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20261001115836_AddSeedContacts")]
    partial class AddSeedContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AgendaContactos.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contactos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ana@ejemplo.com",
                            Nombre = "Ana García",
                            Telefono = "600111222"
                        },
                        new
                        {
                            Id = 2,
                            Email = "luis@ejemplo.com",
                            Nombre = "Luis Pérez",
                            Telefono = "600333444"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@ejemplo.com",
                            Nombre = "María López",
                            Telefono = "600555666"
                        },
                        new
                        {
                            Id = 4,
                            Email = "carlos@ejemplo.com",
                            Nombre = "Carlos Ruiz",
                            Telefono = "600777888"
                        },
                        new
                        {
                            Id = 5,
                            Email = "laura@ejemplo.com",
                            Nombre = "Laura Fernández",
                            Telefono = "600999000"
                        },
                        new
                        {
                            Id = 6,
                            Email = "javier@ejemplo.com",
                            Nombre = "Javier Sánchez",
                            Telefono = "601111222"
                        },
                        new
                        {
                            Id = 7,
                            Email = "elena@ejemplo.com",
                            Nombre = "Elena Martín",
                            Telefono = "601333444"
                        },
                        new
                        {
                            Id = 8,
                            Email = "david@ejemplo.com",
                            Nombre = "David Gómez",
                            Telefono = "601555666"
                        },
                        new
                        {
                            Id = 9,
                            Email = "sara@ejemplo.com",
                            Nombre = "Sara Jiménez",
                            Telefono = "601777888"
                        },
                        new
                        {
                            Id = 10,
                            Email = "pablo@ejemplo.com",
                            Nombre = "Pablo Díaz",
                            Telefono = "601999000"
                        },
                        new
                        {
                            Id = 11,
                            Email = "lucia@ejemplo.com",
                            Nombre = "Lucía Torres",
                            Telefono = "602111222"
                        },
                        new
                        {
                            Id = 12,
                            Email = "alberto@ejemplo.com",
                            Nombre = "Alberto Ruiz",
                            Telefono = "602333444"
                        },
                        new
                        {
                            Id = 13,
                            Email = "carmen@ejemplo.com",
                            Nombre = "Carmen Vega",
                            Telefono = "602555666"
                        },
                        new
                        {
                            Id = 14,
                            Email = "raul@ejemplo.com",
                            Nombre = "Raúl Moreno",
                            Telefono = "602777888"
                        },
                        new
                        {
                            Id = 15,
                            Email = "marta@ejemplo.com",
                            Nombre = "Marta Romero",
                            Telefono = "602999000"
                        },
                        new
                        {
                            Id = 16,
                            Email = "sergio@ejemplo.com",
                            Nombre = "Sergio Navarro",
                            Telefono = "603111222"
                        },
                        new
                        {
                            Id = 17,
                            Email = "nuria@ejemplo.com",
                            Nombre = "Nuria Gil",
                            Telefono = "603333444"
                        },
                        new
                        {
                            Id = 18,
                            Email = "andres@ejemplo.com",
                            Nombre = "Andrés Serrano",
                            Telefono = "603555666"
                        },
                        new
                        {
                            Id = 19,
                            Email = "paula@ejemplo.com",
                            Nombre = "Paula Molina",
                            Telefono = "603777888"
                        },
                        new
                        {
                            Id = 20,
                            Email = "ivan@ejemplo.com",
                            Nombre = "Iván Castro",
                            Telefono = "603999000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
