// <auto-generated />
using System;
using AgendaContactos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaContactos.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20261002093129_AddUsuarioIdToContacto")]
    partial class AddUsuarioIdToContacto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AgendaContactos.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apodo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AgendaContactos.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Apodo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contactos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "García",
                            Apodo = "La Jefa",
                            Email = "ana@ejemplo.com",
                            Favorito = true,
                            Nombre = "Ana",
                            Telefono = "600111222"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Pérez",
                            Apodo = "Luisito",
                            Email = "luis@ejemplo.com",
                            Favorito = false,
                            Nombre = "Luis",
                            Telefono = "600333444"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "López",
                            Apodo = "Mery",
                            Email = "maria@ejemplo.com",
                            Favorito = true,
                            Nombre = "María",
                            Telefono = "600555666"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Ruiz",
                            Apodo = "Carlitos",
                            Email = "carlos@ejemplo.com",
                            Favorito = false,
                            Nombre = "Carlos",
                            Telefono = "600777888"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Fernández",
                            Apodo = "Laurita",
                            Email = "laura@ejemplo.com",
                            Favorito = false,
                            Nombre = "Laura",
                            Telefono = "600999000"
                        },
                        new
                        {
                            Id = 6,
                            Apellidos = "Sánchez",
                            Apodo = "Javi",
                            Email = "javier@ejemplo.com",
                            Favorito = true,
                            Nombre = "Javier",
                            Telefono = "601111222"
                        },
                        new
                        {
                            Id = 7,
                            Apellidos = "Martín",
                            Apodo = "Elenita",
                            Email = "elena@ejemplo.com",
                            Favorito = false,
                            Nombre = "Elena",
                            Telefono = "601333444"
                        },
                        new
                        {
                            Id = 8,
                            Apellidos = "Gómez",
                            Apodo = "Davo",
                            Email = "david@ejemplo.com",
                            Favorito = false,
                            Nombre = "David",
                            Telefono = "601555666"
                        },
                        new
                        {
                            Id = 9,
                            Apellidos = "Jiménez",
                            Apodo = "Sarita",
                            Email = "sara@ejemplo.com",
                            Favorito = true,
                            Nombre = "Sara",
                            Telefono = "601777888"
                        },
                        new
                        {
                            Id = 10,
                            Apellidos = "Díaz",
                            Apodo = "Pablito",
                            Email = "pablo@ejemplo.com",
                            Favorito = false,
                            Nombre = "Pablo",
                            Telefono = "601999000"
                        },
                        new
                        {
                            Id = 11,
                            Apellidos = "Torres",
                            Apodo = "Lucy",
                            Email = "lucia@ejemplo.com",
                            Favorito = false,
                            Nombre = "Lucía",
                            Telefono = "602111222"
                        },
                        new
                        {
                            Id = 12,
                            Apellidos = "Ruiz",
                            Apodo = "Alber",
                            Email = "alberto@ejemplo.com",
                            Favorito = false,
                            Nombre = "Alberto",
                            Telefono = "602333444"
                        },
                        new
                        {
                            Id = 13,
                            Apellidos = "Vega",
                            Apodo = "Carmencita",
                            Email = "carmen@ejemplo.com",
                            Favorito = true,
                            Nombre = "Carmen",
                            Telefono = "602555666"
                        },
                        new
                        {
                            Id = 14,
                            Apellidos = "Moreno",
                            Apodo = "Raulito",
                            Email = "raul@ejemplo.com",
                            Favorito = false,
                            Nombre = "Raúl",
                            Telefono = "602777888"
                        },
                        new
                        {
                            Id = 15,
                            Apellidos = "Romero",
                            Apodo = "Martita",
                            Email = "marta@ejemplo.com",
                            Favorito = false,
                            Nombre = "Marta",
                            Telefono = "602999000"
                        },
                        new
                        {
                            Id = 16,
                            Apellidos = "Navarro",
                            Apodo = "Sergi",
                            Email = "sergio@ejemplo.com",
                            Favorito = false,
                            Nombre = "Sergio",
                            Telefono = "603111222"
                        },
                        new
                        {
                            Id = 17,
                            Apellidos = "Gil",
                            Apodo = "Nuri",
                            Email = "nuria@ejemplo.com",
                            Favorito = true,
                            Nombre = "Nuria",
                            Telefono = "603333444"
                        },
                        new
                        {
                            Id = 18,
                            Apellidos = "Serrano",
                            Apodo = "Andresito",
                            Email = "andres@ejemplo.com",
                            Favorito = false,
                            Nombre = "Andrés",
                            Telefono = "603555666"
                        },
                        new
                        {
                            Id = 19,
                            Apellidos = "Molina",
                            Apodo = "Paulita",
                            Email = "paula@ejemplo.com",
                            Favorito = false,
                            Nombre = "Paula",
                            Telefono = "603777888"
                        },
                        new
                        {
                            Id = 20,
                            Apellidos = "Castro",
                            Apodo = "Ivanito",
                            Email = "ivan@ejemplo.com",
                            Favorito = false,
                            Nombre = "Iván",
                            Telefono = "603999000"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityPasskeyData", b =>
                {
                    b.Property<byte[]>("AttestationObject")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ClientDataJson")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBackupEligible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("SignCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Transports")
                        .HasColumnType("TEXT");

                    b.ToTable("IdentityPasskeyData");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AgendaContactos.Models.Contacto", b =>
                {
                    b.HasOne("AgendaContactos.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgendaContactos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgendaContactos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaContactos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgendaContactos.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
